name: Build & Deploy
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
      - name: Deploy
        run: |
          mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
          ssh-keyscan ${{secrets.SSH_HOST}} >> ~/.ssh/known_hosts
          echo "${{secrets.SSH_PRIVATE_KEY}}" > deploy_key
          chmod 600 ./deploy_key
          echo "${{secrets.DOTENV}}" > .env
          chmod 600 ./.env
          scp target/release/second-brain "${{secrets.SSH_USER}}@{{secrets.SSH_HOST}}:/${{secrets.DEST_PATH}}/"
          rsync -av --delete -e 'ssh -i ./deploy_key' static/ "${{secrets.SSH_USER}}@${{secrets.SSH_HOST}}:/${{secrets.DEST_PATH}}/static
